/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyLichThiGUI;

import Model.LichThi;
import Model.HocSinh;
import static Engine.DBLichThiEngine.SVFromFile;
import static Engine.DBLichThiEngine.getListSVById;
import static Engine.DBLichThiEngine.writeFile;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class ThiSinhGUI extends javax.swing.JFrame {

    /**
     * Creates new form THISINH
     */
    List<HocSinh> listHS;
    List<String> listMHS;
    List<LichThi> listLichThi;
    LichThi lichthi;
    static DefaultTableModel tbThiSinh;
    static String fileName = "src/SavedData/DSLichThi.txt";
    static String fileHS = "src/SavedData/DSHocSinh.txt";
    private ThemThiSinhGUI themThiSinh;

    public ThiSinhGUI(List listMaHS, LichThi lichthiFromParent, List<LichThi> list) {
        initComponents();
        setLocationRelativeTo(null);
        txtKyThi1.setEditable(false);
        txtMonThi1.setEditable(false);
        txCaThi1.setEditable(false);
        txtNgayThi1.setEditable(false);
        lichthi = lichthiFromParent;
        txtKyThi1.setText(lichthi.getTenKyThi());
        txtMonThi1.setText(lichthi.getMonThi());
        txCaThi1.setText(lichthi.getCaThi());
        txtNgayThi1.setText(lichthi.getNgayThi());
        listHS = new ArrayList<>();
        this.listLichThi = list;
        listMHS = listMaHS;
        tbThiSinh = (DefaultTableModel) tableThiSinh.getModel();
        try {
            listHS = SVFromFile(fileHS);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        showTableDataTS();
    }

    public ThiSinhGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtMonThi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKyThi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMonThi1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThiSinh = new javax.swing.JTable();
        btnXoaThiSinh = new javax.swing.JButton();
        txtKyThi1 = new javax.swing.JTextField();
        btnThemThiSinh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txCaThi1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayThi1 = new javax.swing.JTextField();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Môn thi");

        txtMonThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên kỳ thi");

        txtKyThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý danh sách thí sinh");

        btnBack.setBackground(new java.awt.Color(0, 158, 15));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Quay lại");
        btnBack.setMaximumSize(new java.awt.Dimension(86, 27));
        btnBack.setMinimumSize(new java.awt.Dimension(86, 27));
        btnBack.setPreferredSize(new java.awt.Dimension(86, 27));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Môn thi");

        txtMonThi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên kỳ thi");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Danh sách thí sinh");

        tableThiSinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableThiSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã học sinh", "Họ tên", "Giới tính", "Lớp", "Danh hiệu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableThiSinh);
        if (tableThiSinh.getColumnModel().getColumnCount() > 0) {
            tableThiSinh.getColumnModel().getColumn(1).setMinWidth(200);
            tableThiSinh.getColumnModel().getColumn(3).setMinWidth(120);
            tableThiSinh.getColumnModel().getColumn(4).setMinWidth(80);
        }

        btnXoaThiSinh.setBackground(new java.awt.Color(255, 0, 0));
        btnXoaThiSinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaThiSinh.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaThiSinh.setLabel("Xóa thí sinh");
        btnXoaThiSinh.setMaximumSize(new java.awt.Dimension(141, 27));
        btnXoaThiSinh.setMinimumSize(new java.awt.Dimension(141, 27));
        btnXoaThiSinh.setPreferredSize(new java.awt.Dimension(208, 27));
        btnXoaThiSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThiSinhActionPerformed(evt);
            }
        });

        txtKyThi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnThemThiSinh.setBackground(new java.awt.Color(0, 158, 15));
        btnThemThiSinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemThiSinh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemThiSinh.setText("Thêm thí sinh");
        btnThemThiSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThiSinhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ca thi");

        txCaThi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày thi");

        txtNgayThi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThemThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnXoaThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtKyThi1)
                                .addComponent(txCaThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(22, 22, 22)
                                    .addComponent(txtMonThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNgayThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMonThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtKyThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txCaThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            new QuanLyLichThiGUI().setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(ThiSinhGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnXoaThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThiSinhActionPerformed
        int[] selectedRows = tableThiSinh.getSelectedRows();
        boolean checkRemove = false;
        if (selectedRows.length <= 0) {
            JOptionPane.showMessageDialog(this, "Hãy chọn ít nhất một dòng để xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa các dòng đã chọn?", "Xác nhận xóa", JOptionPane.INFORMATION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                List<String> needToRemove = new ArrayList<>();
                for (int row : selectedRows) {
                    needToRemove.add(lichthi.getListHS().get(row));
                }
                for (LichThi lich : listLichThi) {
                    if (lich.equals(this.lichthi)) {
                        lich.xoaHS(needToRemove);
                        break;
                    }
                }
                showTableDataTS();
                JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                try {
                    writeFile(fileName, listLichThi);
                } catch (Exception ex) {
                    Logger.getLogger(QuanLyLichThiGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnXoaThiSinhActionPerformed

    private void btnThemThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThiSinhActionPerformed
        if (themThiSinh == null || !themThiSinh.isVisible()) {
            themThiSinh = new ThemThiSinhGUI(listMHS, lichthi, listLichThi, this);
            themThiSinh.setVisible(true);
        }
    }//GEN-LAST:event_btnThemThiSinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showTableDataTS() {
        tbThiSinh.setRowCount(0);
        List<HocSinh> listShow = new ArrayList<>();
        for (int i = 0; i < listMHS.size(); i++) {
            listShow.add(getListSVById(listHS, listMHS.get(i)));
        }
        for (HocSinh sv : listShow) {
            tbThiSinh.addRow(new Object[]{sv.getMaHS(), sv.getHoTen(), sv.getGioiTinh(), sv.getLop(), sv.getCongTacDoan()});
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThiSinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThiSinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThiSinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThiSinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThiSinhGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnThemThiSinh;
    private javax.swing.JButton btnXoaThiSinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThiSinh;
    private javax.swing.JTextField txCaThi1;
    private javax.swing.JTextField txtKyThi;
    private javax.swing.JTextField txtKyThi1;
    private javax.swing.JTextField txtMonThi;
    private javax.swing.JTextField txtMonThi1;
    private javax.swing.JTextField txtNgayThi1;
    // End of variables declaration//GEN-END:variables
}
